### ISSUE TITLE
Support for multiple devices in one time

### ISSUE THREAD

**Issue by STFBEE** [ashishb/adb-enhanced#128]
At current moment all scripts fails, if you have connected 2 or more devices, so it need to be realised. For example - show the list of connected devices (with or without rich description) and ask the user for index number (or array of indexes), for this device you need to apply the command

**Comment by ashishb** [comment]
The code fails gracefully at this point. Telling you to select a device with `-s`, didn't that happen with you?
https://github.com/ashishb/adb-enhanced/blob/1aedc71868a1ad5f4b2fd05201a1a8507e38b91a/adbe/adb_helper.py#L191

There are multiple problems dealing with multiple devices where the solution is very context-specific. For example, you are deleting `/sdcard/tmp1.jpg` file and that succeeds one device, fails on another due to lack of file permissions, and fails on the third since the file does not exist. There there are commands like changing runtime permissions which work on certain API version and later, in those cases, it does become fairly complicated to decide what to output. That's why, I, intentionally, didn't want to support more than one device. My belief is that if someone is doing automation and using multiple devices they can write a script on top of that. This isn't a final decision in any way, I am open to changing it if you have more ideas in mind.

**Comment by ashishb** [comment]
Closing it for the lack of further conversation.
